
name: Linters

on: [push, pull_request]
jobs:
  isort:
    name: Check imports order
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run isort
        uses: isort/isort-action@master
        with:
          configuration: "."
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Sort imports"
  black_formatter:
    name: Run Black formatter
    runs-on: ubuntu-latest
    needs: [isort]
    steps:
      - uses: actions/checkout@v2
      - name: Check files with black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Automated Commit"
  flake8_linter:
    name: Flake8 linter
    runs-on: ubuntu-latest
    needs: [black_formatter]
    steps:
      - uses: actions/checkout@v3
      - name: Setup python environment.
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Pull modifications
        run: git pull
      - name: Check files with flake8 linter
        uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          max-line-length: "100"
          path: "src" # tests ??
  mypy_type_check:
    name: MyPy type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: MyPy
        run: |
          mypy src/

